(()=>{
const API='https://itunes.apple.com/search';
const input=document.getElementById('searchInput'),button=document.getElementById('searchButton'),results=document.getElementById('results'),title=document.getElementById('resultsTitle'),kicker=document.getElementById('resultsKicker'),count=document.getElementById('resultCount'),type=document.getElementById('mediaType');
let activeAudio=null,activeButton=null,request=0;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const upgrade=u=>String(u||'').replace(/100x100bb\./,'600x600bb.');
const card=(x,i)=>{const art=upgrade(x.artworkUrl100),name=x.trackName||x.collectionName||'Untitled',artist=x.artistName||'Unknown artist',album=x.collectionName||'Single',preview=x.previewUrl||'';return `<article class="result-card"><div class="cover"><img src="${esc(art)}" alt="${esc(name)} artwork" loading="lazy" onerror="this.style.display='none'"></div><div class="result-info"><div class="result-type">${x.wrapperType==='collection'?'ALBUM':'TRACK'} / ${String(i+1).padStart(2,'0')}</div><h3 title="${esc(name)}">${esc(name)}</h3><p title="${esc(artist)}">${esc(artist)}</p><div class="result-actions">${preview?`<button class="preview" data-preview="${esc(preview)}">PREVIEW ▶</button>`:''}<button data-search="${esc(artist)}">MORE ↗</button></div></div></article>`};
async function search(q,heading){const id=++request;results.innerHTML='<div class="loading"><span></span><span></span><span></span> SEARCHING THE RECORDS…</div>';kicker.textContent=q?'SEARCH RESULT':'MELO FINDS';title.textContent=heading||'START HERE.';try{const p=new URLSearchParams({term:q||'alternative music',country:'US',media:'music',entity:type.value==='album'?'album':'song',limit:'24'});const r=await fetch(`${API}?${p}`,{cache:'no-store'});if(!r.ok)throw Error();const data=await r.json();if(id!==request)return;const list=(data.results||[]).filter(x=>x.artworkUrl100);count.textContent=`${list.length} FINDS`;results.innerHTML=list.length?list.map(card).join(''):'<div class="loading">NO RECORDS FOUND. TRY ANOTHER RABBIT HOLE.</div>';bind();results.scrollIntoView({behavior:'smooth',block:'start'})}catch{if(id!==request)return;count.textContent='OFFLINE';results.innerHTML='<div class="loading">THE LIBRARY IS QUIET RIGHT NOW.<br><small>Try again in a moment.</small></div>'}}
function bind(){results.querySelectorAll('[data-preview]').forEach(b=>b.onclick=()=>{if(activeAudio){activeAudio.pause();activeAudio.currentTime=0}if(activeButton===b){activeAudio=null;activeButton=null;b.classList.remove('previewing');b.textContent='PREVIEW ▶';return}activeAudio=new Audio(b.dataset.preview);activeAudio.volume=.72;activeButton=b;b.classList.add('previewing');b.textContent='PLAYING ···';activeAudio.play().catch(()=>{});activeAudio.onended=()=>{b.classList.remove('previewing');b.textContent='PREVIEW ▶';activeAudio=null;activeButton=null}});results.querySelectorAll('[data-search]').forEach(b=>b.onclick=()=>{input.value=b.dataset.search;search(b.dataset.search,`MORE FROM ${b.dataset.search.toUpperCase()}.`)})}
function go(){const q=input.value.trim();search(q,q?`FOUND: ${q.toUpperCase()}.`:'START HERE.')}
button.onclick=go;input.addEventListener('keydown',e=>{if(e.key==='Enter')go()});type.onchange=()=>{const q=input.value.trim();search(q,q?`FOUND: ${q.toUpperCase()}.`:'START HERE.')};document.querySelectorAll('[data-query]').forEach(b=>b.onclick=()=>{input.value=b.dataset.query;go()});document.querySelectorAll('[data-mood]').forEach(b=>b.onclick=()=>{input.value=b.dataset.mood;search(b.dataset.mood,`${b.querySelector('b')?.textContent||'MOOD'} / PICKS.`)});
const cursor=document.getElementById('cursor');if(cursor){window.addEventListener('pointermove',e=>{cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px'});document.addEventListener('pointerover',e=>{if(e.target.closest('a,button,input,select'))cursor.classList.add('big')});document.addEventListener('pointerout',e=>{if(e.target.closest('a,button,input,select'))cursor.classList.remove('big')})}
search('', 'START HERE.');
})();
