(()=>{
const API_MIRRORS=['https://de1.api.radio-browser.info','https://nl1.api.radio-browser.info','https://at1.api.radio-browser.info'];
const audio=document.getElementById('audio'),playBtn=document.getElementById('playBtn'),volume=document.getElementById('volume'),results=document.getElementById('resultsGrid'),featured=document.getElementById('featuredGrid'),favorites=document.getElementById('favoritesGrid'),history=document.getElementById('history'),search=document.getElementById('search'),country=document.getElementById('country'),sort=document.getElementById('sort');
let stations=[],index=-1,active=null,requestId=0;
const keyFav='melo-radio-favorites-v1',keyHist='melo-radio-history-v1';
const getStore=k=>{try{return JSON.parse(localStorage.getItem(k)||'[]')}catch{return[]}};
const setStore=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const favIds=()=>new Set(getStore(keyFav));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const clean=s=>String(s||'').split(',').map(x=>x.trim()).filter(Boolean).slice(0,4);
const initials=s=>String(s?.name||'MELO').replace(/[^\p{L}\p{N}\s]/gu,' ').trim().split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'MELO';
const domainOf=url=>{try{return new URL(url).hostname.replace(/^www\./,'')}catch{return''}};
const imageSources=s=>{const out=[];if(s?.favicon)out.push(s.favicon);const host=domainOf(s?.homepage||s?.url_resolved);if(host){out.push(`https://${host}/favicon.ico`);out.push(`https://www.google.com/s2/favicons?domain=${encodeURIComponent(host)}&sz=256`);out.push(`https://icons.duckduckgo.com/ip3/${encodeURIComponent(host)}.ico`);out.push(`https://wsrv.nl/?url=${encodeURIComponent(`https://${host}/favicon.ico`)}&w=640&h=360&fit=cover`)}return[...new Set(out.filter(Boolean))]};
async function api(path){let last;for(const base of API_MIRRORS){try{const r=await fetch(base+path,{headers:{Accept:'application/json'}});if(!r.ok)throw Error(r.status);return await r.json()}catch(e){last=e}}throw last||Error('Radio service unavailable')}
function normalize(list){return (Array.isArray(list)?list:[]).filter(s=>s&&s.stationuuid&&s.url_resolved&&s.lastcheckok!==0&&s.hls!==1&&/^https:\/\//i.test(s.url_resolved)).filter((s,i,a)=>a.findIndex(x=>x.stationuuid===s.stationuuid)===i)}
function card(s){const fav=favIds().has(s.stationuuid),tags=clean(s.tags).join(' · ')||'LIVE RADIO',sources=imageSources(s);return `<article class="station"><div class="station-cover"><span class="station-fallback">${esc(initials(s))}</span><span class="station-art" data-art-sources="${esc(JSON.stringify(sources))}" aria-hidden="true"></span></div><div class="station-title" title="${esc(s.name)}">${esc(s.name||'Unknown station')}</div><div class="station-meta">${esc(s.country||'Worldwide')} · ${esc(String(s.bitrate||'—'))} kbps · ${esc(tags)}</div><div class="station-bottom"><button class="station-play" data-play="${esc(s.stationuuid)}">LISTEN ↗</button><button class="fav ${fav?'on':''}" data-fav="${esc(s.stationuuid)}" aria-label="${fav?'Remove from':'Add to'} favourites">${fav?'♥':'♡'}</button></div></article>`}
function bindImages(root){root.querySelectorAll('.station-art[data-art-sources]').forEach(box=>{if(box.dataset.bound)return;box.dataset.bound='1';let sources=[];try{sources=JSON.parse(box.dataset.artSources||'[]')}catch{}const tryNext=()=>{if(!sources.length)return;const src=sources.shift(),img=new Image();img.alt='';img.loading='lazy';img.onload=()=>{box.replaceChildren(img);box.classList.add('loaded')};img.onerror=tryNext;img.src=src};tryNext()})}
function bindCards(root){root.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>{const s=find(b.dataset.play);if(s)playStation(s)});root.querySelectorAll('[data-fav]').forEach(b=>b.onclick=()=>toggleFav(b.dataset.fav));bindImages(root)}
function find(id){return stations.find(s=>s.stationuuid===id)||getStore(keyHist).map(x=>x.station).find(s=>s.stationuuid===id)||null}
function render(list,root){root.innerHTML=list.length?list.map(card).join(''):'<div class="empty">No live stations matched that signal.<br><small>Try another genre, country or search term.</small></div>';bindCards(root)}
function renderFavorites(){const ids=favIds(),pool=[...stations,...getStore(keyHist).map(x=>x.station)],unique=[];pool.forEach(s=>{if(s&&ids.has(s.stationuuid)&&!unique.some(x=>x.stationuuid===s.stationuuid))unique.push(s)});document.getElementById('favCount').textContent=`${unique.length} SAVED`;render(unique,favorites)}
function renderHistory(){const h=getStore(keyHist);if(!h.length){history.innerHTML='<div class="empty">Nothing here yet.<br><small>Stations you listen to will appear here.</small></div>';return}history.innerHTML=h.slice(0,12).map((x,i)=>`<div class="history-row"><span>${String(i+1).padStart(2,'0')}</span><div><b>${esc(x.station.name)}</b><small>${esc(x.station.country||'Worldwide')}</small></div><span class="history-meta">${esc(clean(x.station.tags).slice(0,2).join(' · ')||'LIVE')}</span><span class="history-meta">${new Date(x.at).toLocaleDateString()}</span><button data-history-play="${esc(x.station.stationuuid)}">PLAY</button></div>`).join('');history.querySelectorAll('[data-history-play]').forEach(b=>b.onclick=()=>{const s=find(b.dataset.historyPlay);if(s)playStation(s)})}
function saveHistory(s){let h=getStore(keyHist).filter(x=>x.station?.stationuuid!==s.stationuuid);h.unshift({station:s,at:Date.now()});setStore(keyHist,h.slice(0,20));renderHistory();renderFavorites()}
function toggleFav(id){let f=getStore(keyFav);if(f.includes(id))f=f.filter(x=>x!==id);else f.unshift(id);setStore(keyFav,f);renderFavorites();render(resultsList,results);render(featuredList,featured)}
let resultsList=[],featuredList=[];
async function searchStations(){const q=search.value.trim(),cc=country.value,order=sort.value;results.innerHTML='<div class="loading">SCANNING THE AIRWAVES…</div>';const rid=++requestId;try{let p=new URLSearchParams({limit:'28',hidebroken:'true',is_https:'true',order,reverse:'true'});if(q)p.set('name',q);if(cc)p.set('country',cc);const list=normalize(await api('/json/stations/search?'+p.toString()));if(rid!==requestId)return;resultsList=list;stations=[...stations,...list];render(list,results)}catch(e){results.innerHTML='<div class="empty">RADIO DIRECTORY OFFLINE.<br><small>The public station directory could not be reached right now.</small></div>'}}
async function loadCountries(){try{const list=await api('/json/countries?order=stationcount&reverse=true&limit=80');country.innerHTML='<option value="">ALL COUNTRIES</option>'+list.map(c=>`<option value="${esc(c.name)}">${esc(c.name)} · ${c.stationcount}</option>`).join('')}catch{}}
async function loadTag(tag){try{const p=new URLSearchParams({tag,limit:'8',hidebroken:'true',is_https:'true',order:'clickcount',reverse:'true'});return normalize(await api('/json/stations/search?'+p))}catch{return[]}}
async function loadFeatured(){featured.innerHTML='<div class="loading">TUNING THE DIAL…</div>';try{const tags=['chill','lofi','jpop','dream','indie','pop'],chunks=await Promise.all(tags.map(loadTag)),all=[];chunks.flat().forEach(s=>{if(!all.some(x=>x.stationuuid===s.stationuuid))all.push(s)});featuredList=all.slice(0,12);stations=[...stations,...featuredList];render(featuredList,featured);renderFavorites()}catch{featured.innerHTML='<div class="empty">MELO PICKS are taking a quiet moment.</div>'}}
async function mood(tag){featured.innerHTML='<div class="loading">TUNING '+tag.toUpperCase()+'…</div>';const list=await loadTag(tag);featuredList=list;stations=[...stations,...list];render(list,featured);renderFavorites();document.querySelector('.section-head')?.scrollIntoView({behavior:'smooth',block:'start'})}
function updateNow(s){const meta=[s.country||'Worldwide',s.codec||'LIVE',s.bitrate?`${s.bitrate} kbps`:''].filter(Boolean).join(' · ');document.getElementById('nowName').textContent=s.name||'Live radio';document.getElementById('nowMeta').textContent=meta;document.getElementById('heroStation').textContent=s.name||'Live radio';document.getElementById('heroMeta').textContent=`${s.country||'WORLDWIDE'} / ${s.codec||'LIVE'}${s.bitrate?' / '+s.bitrate+' KBPS':''}`;document.getElementById('nowTags').innerHTML=clean(s.tags).map(t=>`<span class="chip">${esc(t)}</span>`).join('');const art=document.getElementById('nowArt');art.innerHTML=`<span>${esc(initials(s))}</span>`;const sources=imageSources(s);if(sources.length){const tryNow=i=>{if(i>=sources.length)return;const img=new Image();img.alt=s.name||'Station artwork';img.onload=()=>{art.appendChild(img)};img.onerror=()=>tryNow(i+1);img.src=sources[i]};tryNow(0)}if('mediaSession'in navigator){try{navigator.mediaSession.metadata=new MediaMetadata({title:s.name||'MELO Radio',artist:s.country||'Live Radio',album:'MELO RADIO',artwork:s.favicon?[{src:s.favicon}]:[]})}catch{}}}
async function playStation(s){active=s;index=stations.findIndex(x=>x.stationuuid===s.stationuuid);updateNow(s);saveHistory(s);playBtn.textContent='…';try{await api('/json/url/'+encodeURIComponent(s.stationuuid));}catch{}audio.src=s.url_resolved;audio.load();try{await audio.play();playBtn.textContent='❚❚'}catch{playBtn.textContent='▶';document.getElementById('nowMeta').textContent='This station refused playback in the browser. Try another signal.'}}
function toggle(){if(!active){const s=stations[0]||featuredList[0];if(s)playStation(s);return}if(audio.paused){audio.play().then(()=>playBtn.textContent='❚❚').catch(()=>{})}else{audio.pause();playBtn.textContent='▶'}}
function move(dir){if(!stations.length)return;index=Math.max(0,Math.min(stations.length-1,index+dir));playStation(stations[index])}
playBtn.onclick=toggle;document.getElementById('prevBtn').onclick=()=>move(-1);document.getElementById('nextBtn').onclick=()=>move(1);volume.oninput=()=>audio.volume=Number(volume.value)/100;audio.volume=.78;audio.onplay=()=>playBtn.textContent='❚❚';audio.onpause=()=>playBtn.textContent='▶';audio.onerror=()=>{playBtn.textContent='▶';if(active)document.getElementById('nowMeta').textContent='Stream unavailable. Try another station.'};document.getElementById('searchBtn').onclick=searchStations;search.addEventListener('keydown',e=>{if(e.key==='Enter')searchStations()});country.onchange=searchStations;sort.onchange=searchStations;document.getElementById('randomBtn').onclick=()=>{const list=featuredList.length?featuredList:resultsList;if(list.length)playStation(list[Math.floor(Math.random()*list.length)])};document.getElementById('favoritesJump').onclick=()=>document.getElementById('favoritesSection').scrollIntoView({behavior:'smooth'});document.getElementById('clearHistory').onclick=()=>{setStore(keyHist,[]);renderHistory();renderFavorites()};document.querySelectorAll('.mood-grid button').forEach(b=>b.onclick=()=>mood(b.dataset.tag));
loadCountries();loadFeatured();searchStations();renderHistory();renderFavorites();
})();
