(() => {
  const token = new URLSearchParams(location.search).get('token') || '';
  const title = document.getElementById('title');
  const copy = document.getElementById('copy');
  const message = document.getElementById('message');
  const setup = document.getElementById('setup');
  const start = document.getElementById('start');
  const begin = document.getElementById('begin');
  const verify = document.getElementById('verify');
  const username = document.getElementById('username');
  const startUsername = document.getElementById('startUsername');
  const qr = document.getElementById('qr');
  const key = document.getElementById('key');
  const code = document.getElementById('code');
  const copyKey = document.getElementById('copyKey');
  const steps = [...document.querySelectorAll('.step')];

  const api = async (path, body) => {
    const r = await fetch(path, {
      method: 'POST',
      credentials: 'include',
      cache: 'no-store',
      headers: {'Content-Type': 'application/json'},
      body: JSON.stringify(body)
    });
    const d = await r.json().catch(() => ({}));
    if(!r.ok) throw Error(d.error || `Request failed (${r.status}).`);
    return d;
  };

  const info = async () => {
    const r = await fetch(`/api/admin/invite/info?token=${encodeURIComponent(token)}`, {
      credentials: 'include',
      cache: 'no-store'
    });
    const d = await r.json().catch(() => ({}));
    if(!r.ok) throw Error(d.error || `Request failed (${r.status}).`);
    return d;
  };

  const setStep = active => {
    steps.forEach((step, index) => step.classList.toggle('active', index === active));
  };

  if(!token){
    copy.textContent = 'This invitation link is missing its token.';
    start.classList.add('hidden');
    return;
  }

  info().then(d => {
    if(d.configured){
      title.textContent = 'Already configured.';
      copy.textContent = `The Authenticator for ${d.username} is already configured. You can sign in normally.`;
      start.classList.add('hidden');
      return;
    }
    username.textContent = d.username;
    startUsername.textContent = d.username;
    title.innerHTML = `Welcome, <strong>${d.username}</strong>.`;
    copy.textContent = 'You have been invited to MELO as an administrator. Set up your Authenticator to activate your account.';
  }).catch(e => {
    copy.textContent = e.message;
    start.classList.add('hidden');
  });

  begin.onclick = async () => {
    message.className = 'message';
    message.textContent = '';
    begin.disabled = true;
    try {
      const d = await api('/api/admin/invite/setup/start', {token});
      qr.src = d.qrCodeDataUrl;
      key.textContent = d.setupKey;
      setup.classList.remove('hidden');
      start.classList.add('hidden');
      copy.textContent = 'Scan the QR code, then enter the 6-digit code generated by your Authenticator.';
      setStep(1);
      setTimeout(() => code.focus(), 80);
    } catch(e) {
      message.textContent = e.message;
      begin.disabled = false;
    }
  };

  code.addEventListener('input', () => {
    code.value = code.value.replace(/\D/g, '').slice(0, 6);
  });

  code.addEventListener('keydown', event => {
    if(event.key === 'Enter') verify.click();
  });

  copyKey?.addEventListener('click', async () => {
    if(!key.textContent) return;
    try {
      await navigator.clipboard.writeText(key.textContent.trim());
      copyKey.textContent = '✓';
      setTimeout(() => { copyKey.textContent = '⧉'; }, 1400);
    } catch {
      message.textContent = 'Could not copy the setup key. Select it and copy manually.';
    }
  });

  verify.onclick = async () => {
    message.className = 'message';
    message.textContent = '';
    const value = code.value.trim();
    if(!/^\d{6}$/.test(value)){
      message.textContent = 'Enter the current 6-digit Authenticator code.';
      code.focus();
      return;
    }
    verify.disabled = true;
    try {
      const d = await api('/api/admin/invite/setup/verify', {token, code: value});
      setStep(2);
      message.className = 'message success';
      message.textContent = 'Authenticator connected. Entering the Control Room…';
      setTimeout(() => location.href = d.redirect || '/admin/', 500);
    } catch(e) {
      message.textContent = e.message;
      verify.disabled = false;
      code.focus();
    }
  };
})();
