(() => {
  const render = async () => {
    const view = new URLSearchParams(location.search).get('view') || 'dashboard';
    if (view !== 'analytics') return;
    const c=document.getElementById('page-content'); if(!c||typeof api!=='function') return;
    try{
      const d=await api('/api/admin/analytics');
      const events=d.events||[], versions=d.versions||[], platforms=d.platforms||[], days=d.dailyInstallations||[];
      const total=events.reduce((n,x)=>n+Number(x.count||0),0), installs=versions.reduce((n,x)=>n+Number(x.count||0),0);
      const max=Math.max(1,...events.map(x=>Number(x.count||0))), maxDay=Math.max(1,...days.map(x=>Number(x.count||0)));
      c.innerHTML=`<section class="page analytics-page"><div class="page-intro"><h2>Analytics</h2><p>MELO adoption, telemetry volume and fleet distribution — derived from D1.</p></div><section class="metrics">${metric('TELEMETRY EVENTS',total,'All recorded events')}${metric('INSTALLATIONS',installs,'Registered clients')}${metric('EVENT TYPES',events.length,'Observed categories')}${metric('PLATFORMS',platforms.length,'Supported platforms')}</section><div class="two-col"><section class="panel"><div class="panel-head"><h2>Event volume</h2><span>ALL TIME</span></div><div class="bar-list">${events.length?events.map(x=>`<div class="bar-row"><span>${esc(String(x.event_type).toUpperCase())}</span><div><i style="width:${Math.max(3,Number(x.count)/max*100)}%"></i></div><b>${esc(x.count)}</b></div>`).join(''):'<div class="empty">No telemetry events.</div>'}</div></section><section class="panel"><div class="panel-head"><h2>Fleet versions</h2><span>INSTALLATIONS</span></div><table class="data-table"><thead><tr><th>VERSION</th><th>INSTALLATIONS</th><th>SHARE</th></tr></thead><tbody>${versions.length?versions.map(x=>`<tr><td class="mono">${esc(x.app_version)}</td><td class="accent">${esc(x.count)}</td><td class="mono">${installs?Math.round(Number(x.count)/installs*100):0}%</td></tr>`).join(''):'<tr><td colspan="3">No versions.</td></tr>'}</tbody></table></section></div><div class="two-col"><section class="panel"><div class="panel-head"><h2>Platform distribution</h2><span>FLEET</span></div><table class="data-table"><tbody>${platforms.length?platforms.map(x=>`<tr><td class="mono">${esc(String(x.platform).toUpperCase())}</td><td class="accent">${esc(x.count)}</td><td class="mono">${installs?Math.round(Number(x.count)/installs*100):0}%</td></tr>`).join(''):'<tr><td>No platform data.</td></tr>'}</tbody></table></section><section class="panel"><div class="panel-head"><h2>New installations</h2><span>LAST 30 DAYS</span></div><div class="bar-list daily-bars">${days.length?days.slice().reverse().map(x=>`<div class="bar-row"><span>${esc(String(x.day))}</span><div><i style="width:${Math.max(3,Number(x.count)/maxDay*100)}%"></i></div><b>${esc(x.count)}</b></div>`).join(''):'<div class="empty">No installations in the last 30 days.</div>'}</div></section></div><div class="health-strip"><span><strong>LIVE D1 ANALYTICS.</strong> No account identity or personal content is included.</span><span class="right">AUTO REFRESH 30S</span></div></section>`;
    }catch(e){c.innerHTML=`<section class="page"><div class="empty">Unable to load analytics. ${esc(e.message)}</div></section>`}
  };
  window.addEventListener('popstate',render); setTimeout(render,0); setInterval(render,30000);
})();
