(() => {
  const out = document.getElementById('terminal-output');
  const input = document.getElementById('console-input');
  const form = document.getElementById('console-form');
  const suggestions = document.getElementById('suggestions');
  const streamOut = document.getElementById('stream-output');
  const streamToggle = document.getElementById('stream-toggle');
  const commands = ['help','status','health','stats','stats --today','users','users --active','installations','installations --recent','reports','reports --open','version','uptime','clear','about'];
  const history = []; let historyIndex = -1; let streamPaused = false; let lastStream = '';
  const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const api = async (path, params={}) => { const q=new URLSearchParams(params); const r=await fetch(path+(q.toString()?`?${q}`:''),{credentials:'include',cache:'no-store'}); if(r.status===401){location.href='../admin-login.html';throw Error('Authentication required')} if(!r.ok)throw Error(`Request failed (${r.status})`); return r.json(); };
  const stamp=()=>new Date().toLocaleTimeString([], {hour12:false});
  const line=(text='',kind='output')=>{const el=document.createElement('div');el.className=`line ${kind}`;el.innerHTML=`<span class="dim">[${esc(stamp())}]</span> ${text}`;out.appendChild(el);out.scrollTop=out.scrollHeight};
  const table=(rows,cols)=>{if(!rows.length)return '<span class="dim">No records returned.</span>';return rows.map(r=>cols.map(c=>`${c[0]}: ${esc(r[c[1]])}`).join('  ·  ')).join('<br>')};
  function boot(){line('<span class="accent">MELO CONTROL ROOM CONSOLE</span>  <span class="dim">v1 · read-only operations</span>','info');line('Protected session detected. No arbitrary shell, SQL, or destructive commands are available.','info');line('Type <span class="accent">help</span> for commands. Use ↑/↓ for history and Tab for autocomplete.','info');}
  function help(){line('<span class="accent">AVAILABLE COMMANDS</span>');line('  help                         show this command list');line('  status                       control-plane status');line('  health                       Worker + D1 health snapshot');line('  stats [--today]              telemetry and installation statistics');line('  users [--active]             telemetry-backed client population');line('  installations [--recent]    installation fleet');line('  reports [--open]             crash + bug-report overview');line('  version                      current release ledger');line('  uptime                       service runtime information');line('  about                        console and security information');line('  clear                        clear terminal');line('<span class="dim">Arguments are parsed locally, then only whitelisted read-only Admin APIs are called.</span>');}
  async function run(cmd){
    const raw=cmd.trim(); if(!raw)return; history.push(raw);historyIndex=history.length;line(`<span class="prompt">melo@control-room:~$</span> ${esc(raw)}`,'cmd');
    const parts=raw.toLowerCase().split(/\s+/); const base=parts[0]; const arg=parts[1]||'';
    try{
      if(base==='clear'){out.innerHTML='';return} if(base==='help'){help();return} if(base==='about'){line('<span class="accent">MELO Control Room Console</span>');line('Read-only operations interface for the MELO administration surface.');line('Authentication: protected admin session · Data: existing D1-backed Admin APIs.');line('Safety: command allowlist only · no arbitrary execution · no secrets displayed.');return}
      if(!commands.some(c=>c.split(' ')[0]===base)){line(`Unknown command: <span class="warn">${esc(base)}</span>. Type <span class="accent">help</span>.`,'warn');return}
      if(base==='status'){const d=await api('/api/admin/services');const services=d.services||[];line(`<span class="accent">CONTROL PLANE STATUS</span>  ${services.length} service checks`);services.forEach(s=>line(`  ${esc(s.service)}  <span class="good">${esc(s.status)}</span>  ${s.latencyMs==null?'—':esc(s.latencyMs)+' ms'}  <span class="dim">${esc(s.note)}</span>`));return}
      if(base==='health'){const d=await api('/api/admin/health-detail');line(`<span class="accent">SYSTEM HEALTH</span>  generated ${stamp()}`);(d.components||[]).forEach(c=>line(`  ${esc(c.component)}  <span class="${/OK|ACTIVE|OPERATIONAL/i.test(c.status)?'good':'warn'}">${esc(c.status)}</span>  ${esc(c.detail)}`));return}
      if(base==='stats'){const d=await api('/api/admin/dashboard');const m=d.metrics||{},a=d.adoption||{};line('<span class="accent">TELEMETRY STATISTICS</span>');line(`  installations     <b>${esc(m.totalInstallations??0)}</b>`);line(`  active (7d)       <b>${esc(m.activeInstallations??0)}</b>`);line(`  new today         <b>${esc(m.newToday??0)}</b>`);line(`  crash reports     <b>${esc(d.crashes?.total??0)}</b>`);line(`  current version   <span class="accent">${esc(a.currentVersion||'—')}</span>`);if(arg==='--today')line(`  scope              <span class="dim">today / current dashboard window</span>`);return}
      if(base==='users'){const d=await api('/api/admin/users');let rows=d.rows||[];if(arg==='--active')rows=rows.filter(r=>Number(r.last_seen)>=Math.floor(Date.now()/1000)-7*86400);line(`<span class="accent">USERS / CLIENTS</span>  ${rows.length} ${arg==='--active'?'active ':''}records`);line(table(rows.slice(0,20),[['id','installation_id'],['version','app_version'],['last seen','last_seen']]));return}
      if(base==='installations'){const d=await api('/api/admin/installations');let rows=d.rows||[];if(arg==='--recent')rows=rows.sort((a,b)=>Number(b.last_seen||0)-Number(a.last_seen||0)).slice(0,20);line(`<span class="accent">INSTALLATIONS</span>  ${rows.length} records${arg==='--recent'?' · most recent first':''}`);line(table(rows.slice(0,30),[['id','installation_id'],['version','app_version'],['platform','platform'],['last seen','last_seen']]));return}
      if(base==='reports'){const [cr,br]=await Promise.all([api('/api/admin/crashes'),api('/api/admin/bug-reports')]);let crashes=cr.rows||[],bugs=br.rows||br.reports||[];if(arg==='--open')bugs=bugs.filter(r=>!['closed','resolved','done'].includes(String(r.status||'').toLowerCase()));line(`<span class="accent">REPORTS</span>  ${crashes.length} crash records · ${bugs.length} bug reports${arg==='--open'?' · open only':''}`);if(crashes.length)line(`  crashes: <span class="warn">${crashes.slice(0,10).map(r=>esc(r.error_type||'Unhandled crash')).join(' · ')}</span>`);if(bugs.length)line(`  bugs:    ${bugs.slice(0,10).map(r=>esc(r.report_id||r.id||'report')).join(' · ')}`);return}
      if(base==='version'){const d=await api('/api/admin/releases');const rows=d.rows||[];line(`<span class="accent">RELEASE LEDGER</span>  ${rows.length} records`);line(table(rows.slice(0,15),[['version','version'],['build','build'],['platform','platform'],['status','release_status']]));return}
      if(base==='uptime'){const d=await api('/api/admin/services');line('<span class="accent">UPTIME</span>');line('  Cloudflare Worker uses an edge/request runtime; process uptime is not directly measurable.');line(`  control-plane checks: ${esc((d.services||[]).filter(s=>/OK|ACTIVE|OPERATIONAL/i.test(s.status)).length)}/${esc((d.services||[]).length)} operational.`);line('  This console deliberately does not fabricate an uptime counter.');return}
    }catch(e){line(`<span class="error">ERROR</span> ${esc(e.message)}`,'error')}
  }
  function showSuggestions(){const q=input.value.trim().toLowerCase();const matches=commands.filter(c=>c.startsWith(q)).slice(0,8);if(!q||!matches.length){suggestions.hidden=true;return}suggestions.innerHTML=matches.map(c=>`<button type="button" data-command="${esc(c)}">${esc(c)}</button>`).join('');suggestions.hidden=false;suggestions.querySelectorAll('button').forEach(b=>b.onclick=()=>{input.value=b.dataset.command;suggestions.hidden=true;input.focus()})}
  form.addEventListener('submit',e=>{e.preventDefault();const c=input.value;input.value='';suggestions.hidden=true;run(c)});
  input.addEventListener('input',showSuggestions);
  input.addEventListener('keydown',e=>{if(e.key==='ArrowUp'){e.preventDefault();if(history.length){historyIndex=Math.max(0,historyIndex-1);input.value=history[historyIndex]}}else if(e.key==='ArrowDown'){e.preventDefault();if(history.length){historyIndex=Math.min(history.length,historyIndex+1);input.value=history[historyIndex]||''}}else if(e.key==='Tab'){e.preventDefault();const q=input.value.trim().toLowerCase();const m=commands.find(c=>c.startsWith(q));if(m){input.value=m;showSuggestions()}}else if(e.ctrlKey&&e.key.toLowerCase()==='l'){e.preventDefault();out.innerHTML='';suggestions.hidden=true}});
  document.getElementById('clear-output').onclick=()=>out.innerHTML='';
  document.getElementById('copy-output').onclick=async()=>{await navigator.clipboard.writeText(out.innerText);line('<span class="good">Output copied to clipboard.</span>','good')};
  function addStream(rows){if(streamPaused)return;const events=(rows||[]).filter(r=>String(r.event_id||'')!==lastStream);if(!events.length)return;lastStream=String(events[0].event_id||'');streamOut.innerHTML=events.slice(0,30).map(r=>`<div class="stream-row"><span class="time">${esc(new Date(Number(r.timestamp||0)*1000).toLocaleTimeString([], {hour12:false}))}</span><span class="event">${esc(String(r.event_type||'EVENT').toUpperCase())}</span><span>${esc(r.installation_id||'unknown')} · ${esc(r.app_version||'—')} · ${esc(r.platform||'—')}</span></div>`).join('');}
  async function refreshStream(){try{const d=await api('/api/admin/dashboard');addStream(d.recentActivity||[])}catch(e){if(streamOut.querySelector('.stream-empty'))streamOut.innerHTML='<div class="stream-empty">Stream unavailable.</div>'}}
  streamToggle.onclick=()=>{streamPaused=!streamPaused;streamToggle.textContent=streamPaused?'RESUME':'PAUSE'};
  document.getElementById('quick-commands').innerHTML=commands.filter(c=>!['clear','help','about','uptime'].includes(c)).map(c=>`<button class="quick-command" type="button" data-command="${esc(c)}"><b>${esc(c)}</b><span>run read-only query</span></button>`).join('');
  document.querySelectorAll('.quick-command').forEach(b=>b.addEventListener('click',()=>{input.value=b.dataset.command;run(b.dataset.command);input.value=''}));
  setInterval(()=>{const d=new Date();document.getElementById('console-clock').textContent=d.toLocaleTimeString([], {hour12:false})},1000);setInterval(refreshStream,5000);
  boot();refreshStream();input.focus();
})();
