const content=document.getElementById('page-content');
const title=document.getElementById('page-title');
const identity=document.getElementById('identity');
const clock=document.getElementById('clock');
const logout=document.getElementById('logout');

const views={
  dashboard:{title:'MELO Administration',heading:'MELO',copy:'Private administration console · live D1 telemetry'},
  users:{title:'Accounts',heading:'Accounts',copy:'MELO account identity, plans, Spotify connections and moderation.'},
  plans:{title:'Plans',heading:'Plans',copy:'Owner-controlled MELO plan definitions and account distribution.'},
  installations:{title:'Installations',heading:'Installations',copy:'Registered MELO clients and their latest heartbeat state.'},
  crashes:{title:'Crashes',heading:'Crash Logs',copy:'Investigate sanitized crash reports received from MELO clients.'},
  'bug-reports':{title:'Bug Reports',heading:'Bug Reports',copy:'Review manually submitted MELO bug reports.'},
  security:{title:'Security',heading:'Security Center',copy:'Administrative authentication and protected rate-limit activity.'},
  services:{title:'API / Services',heading:'Services',copy:'Current control-plane and telemetry service status.'},
  chat:{title:'Admin Chat',heading:'Admin Chat',copy:'Private shared room for the MELO administration team.'},
  releases:{title:'Releases',heading:'Releases',copy:'Production versions, builds and rollout status recorded in D1.'},
  flags:{title:'Feature Flags',heading:'Feature Flags',copy:'Feature flag state recorded in D1.'},
  analytics:{title:'Analytics',heading:'Analytics',copy:'Adoption and event metrics derived from telemetry.'},
  health:{title:'System Health',heading:'System Health',copy:'Current Worker and D1 health snapshot.'},
  settings:{title:'Admin Settings',heading:'Admin Settings',copy:'Read-only administrative configuration.'},
  audit:{title:'Audit Log',heading:'Audit Log',copy:'Server-side record of administrative actions.'}
};

const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const date=ts=>ts?new Date(Number(ts)*1000).toLocaleString([], {dateStyle:'medium',timeStyle:'short'}):'—';
const ago=ts=>{if(!ts)return'—';const s=Math.max(0,Math.floor(Date.now()/1000)-Number(ts));if(s<60)return`${s}s ago`;if(s<3600)return`${Math.floor(s/60)}m ago`;if(s<86400)return`${Math.floor(s/3600)}h ago`;return`${Math.floor(s/86400)}d ago`};
async function api(path,params={}){const q=new URLSearchParams(params);const r=await fetch(path+(q.toString()?`?${q}`:''),{credentials:'include',cache:'no-store'});if(r.status===401){location.href='../admin-login.html';throw Error('Authentication required')}if(!r.ok)throw Error(`Request failed (${r.status})`);return r.json()}
window.api=api;
function metric(label,value,note){return`<article class="metric"><small>${esc(label)}</small><strong>${esc(value)}</strong><span class="delta">${esc(note)}</span></article>`}

function dashboardHtml(d,releases,accounts){
  const m=d.metrics||{},a=d.adoption||{},p=a.platforms||[],v=a.versions||[],rows=d.recentActivity||[],am=accounts?.metrics||{},accountRows=accounts?.rows||[],releaseRows=releases?.rows||releases?.releases||[],active=releaseRows.find(r=>String(r.release_status||'').toLowerCase()==='active')||releaseRows[0],staged=releaseRows.find(r=>String(r.release_status||'').toLowerCase()==='staged');
  const activity=rows.length?rows.map(r=>`<div class="activity-row"><span class="activity-time">${esc(ago(r.timestamp))}</span><span class="activity-type ok">[${esc(String(r.event_type).toUpperCase())}]</span><span class="activity-text">${esc(r.installation_id)} · ${esc(r.app_version)} · ${esc(r.platform)}</span></div>`).join(''):'<div class="empty">No telemetry activity yet.</div>';
  const adoption=[...p.map(x=>({label:String(x.platform).toUpperCase(),count:Number(x.count),kind:'PLATFORM'})),...v.map(x=>({label:x.app_version,count:Number(x.count),kind:'VERSION'}))];
  const table=adoption.length?adoption.map(x=>`<tr><td class="mono">${esc(x.kind)}</td><td>${esc(x.label)}</td><td class="mono accent">${x.count}</td><td class="mono">${m.totalInstallations?Math.round(x.count/Number(m.totalInstallations)*100):0}%</td></tr>`).join(''):'<tr><td colspan="4">No installation telemetry yet.</td></tr>';
  const activeLabel=active?`${active.version}${active.build?` · ${active.build}`:''}`:'Not configured';
  const stagedLabel=staged?`${staged.version}${staged.build?` · ${staged.build}`:''}`:'None';
  const releaseStatus=active?'ACTIVE':'NO ACTIVE RELEASE';
  return`<section class="page"><div class="hero-line"><div><h2 class="hero-title">MELO <em>control room.</em></h2><p class="hero-copy">Private administration console · live D1 telemetry</p></div><div class="status-large"><i></i>TELEMETRY ONLINE</div></div>
  <section class="metrics">${metric('TOTAL INSTALLATIONS',m.totalInstallations??0,'Registered clients')}${metric('ACTIVE INSTALLATIONS',m.activeInstallations??0,'Seen in last 7 days')}${metric('NEW TODAY',m.newToday??0,'Registered today')}${metric('CRASH REPORTS',d.crashes?.total??0,`${d.crashes?.today??0} today`)}${metric('MELO ACCOUNTS',am.total??0,'Registered accounts')}</section>
  <div class="two-col"><section class="panel"><div class="panel-head"><h2>Installations & adoption</h2><span>LIVE D1 DATA <b class="accent">●</b></span></div><table class="data-table"><thead><tr><th>KIND</th><th>VALUE</th><th>COUNT</th><th>SHARE</th></tr></thead><tbody>${table}<tr><td class="mono">CURRENT</td><td>${esc(a.currentVersion||'—')}</td><td class="mono accent">${esc(a.currentAdoption??0)}%</td><td class="mono">${esc(a.currentReleaseStatus||'not configured')}</td></tr></tbody></table></section>
  <section class="panel"><div class="panel-head"><h2>Recent Activity</h2><span>LIVE TELEMETRY</span></div><div class="activity">${activity}</div></section></div>
  <div class="health-strip"><span><strong>● Telemetry pipeline operational.</strong> Dashboard values are read from D1.</span><span class="right">UPDATED ${esc(date(d.generatedAt))}</span></div>
  <div class="subgrid"><section class="mini-panel"><h3>Accounts</h3><div class="kv"><span>Active</span><b>${esc(am.active??0)}</b></div><div class="kv"><span>Spotify linked</span><b>${esc(am.spotifyLinked??0)}</b></div><div class="kv"><span>Banned / suspended</span><b>${esc((am.banned??0)+(am.suspended??0))}</b></div><a class="dashboard-link" href="/admin/?view=users">MANAGE ACCOUNTS ↗</a></section><section class="mini-panel"><h3>Release Pipeline</h3><div class="kv"><span>Active</span><b>${esc(activeLabel)}</b></div><div class="kv"><span>Status</span><b>${esc(releaseStatus)}</b></div><div class="kv"><span>Staged</span><b>${esc(stagedLabel)}</b></div><a class="dashboard-link" href="/admin/?view=releases">OPEN RELEASES ↗</a></section>
  <section class="mini-panel"><h3>Crash Status</h3><div class="kv"><span>Today</span><b>${esc(d.crashes?.today??0)}</b></div><div class="kv"><span>Total reports</span><b>${esc(d.crashes?.total??0)}</b></div><a class="dashboard-link" href="/admin/?view=crashes">INVESTIGATE CRASHES ↗</a></section>
  <section class="mini-panel"><h3>Security</h3><div class="kv"><span>Failed-auth windows</span><b>${esc(d.security?.failedAuthWindows??0)}</b></div><div class="kv"><span>Sessions</span><b>Protected</b></div><a class="dashboard-link" href="/admin/?view=security">OPEN SECURITY ↗</a></section></div>
  <section class="panel" style="margin-top:10px"><div class="panel-head"><h2>Recent Accounts</h2><span>NEWEST MELO ACCOUNTS</span></div><div class="activity">${accountRows.slice(0,8).map(r=>`<div class="activity-row"><span class="activity-time">${esc(ago(r.created_at))}</span><span class="activity-type ok">[ACCOUNT]</span><span class="activity-text">${esc(r.display_name)} · ${esc(r.email)} · ${esc(String(r.plan_code||'free').toUpperCase())}</span></div>`).join('')||'<div class="empty">No accounts yet.</div>'}</div></section><section class="panel dashboard-control-panel"><div class="panel-head"><h2>Control Plane</h2><span>QUICK STATUS</span></div><div class="control-grid"><a href="/admin/?view=installations"><span>INSTALLATIONS</span><b>${esc(m.totalInstallations??0)}</b><small>Registered clients</small></a><a href="/admin/?view=bug-reports"><span>BUG REPORTS</span><b>${esc(d.bugReports?.total??d.bugs?.total??'—')}</b><small>Open reports</small></a><a href="/admin/?view=analytics"><span>ADOPTION</span><b>${esc(a.currentAdoption??0)}%</b><small>Current release share</small></a><a href="/admin/?view=health"><span>SYSTEM HEALTH</span><b class="good">OK</b><small>Worker + D1 checks</small></a></div></section>
  </section>`;
}

function showServicesLoading(){content.innerHTML=`<section class="page services-page"><div class="page-intro"><h2>API / Services</h2><p>Current control-plane and telemetry service status.</p></div><section class="panel"><div class="panel-head"><h2>Service Status</h2><span>LIVE</span></div><div class="service-list"><div class="service-row"><div><strong>CONTROL ROOM API</strong><span>Checking protected service endpoint…</span></div><b>CHECKING</b></div></div></section></section>`}
async function renderServices(){showServicesLoading();try{const d=await api('/api/admin/health-detail');const services=[['CONTROL ROOM API','Protected administrator request handler',true],['D1 DATABASE','Administrative data store',true],['TELEMETRY INGESTION','Client telemetry ingestion pipeline',true],['CRASH REPORTING','Sanitized crash report ingestion',true]];const detail=Object.entries(d||{});content.innerHTML=`<section class="page services-page"><div class="page-intro"><h2>API / Services</h2><p>Current control-plane and telemetry service status.</p></div><section class="panel"><div class="panel-head"><h2>Service Status</h2><span>LIVE API</span></div><div class="service-list">${services.map(([name,desc])=>`<div class="service-row"><div><strong>${name}</strong><span>${desc}</span></div><b>OPERATIONAL</b></div>`).join('')}</div></section>${detail.length?`<section class="panel service-detail-panel"><div class="panel-head"><h2>Endpoint Detail</h2><span>HEALTH DETAIL</span></div><div class="service-detail-list">${detail.map(([k,v])=>`<div><span>${esc(k.replace(/[_-]+/g,' ').toUpperCase())}</span><b>${esc(typeof v==='object'?JSON.stringify(v):v)}</b></div>`).join('')}</div></section>`:''}<div class="health-strip"><span><strong>SERVICE LAYER ACTIVE.</strong> Values come from the protected health endpoint.</span><span class="right">LIVE</span></div></section>`}catch(e){content.innerHTML=`<section class="page services-page"><div class="page-intro"><h2>API / Services</h2><p>Current control-plane and telemetry service status.</p></div><section class="panel"><div class="empty">Unable to load service status. ${esc(e.message)}</div></section></section>`}}

let currentView='dashboard',refreshTimer;
const specializedViews=new Set(['users','plans','installations','bug-reports','crashes','security','chat','releases','flags','analytics','health','settings','audit']);
function scheduleRefresh(){clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>loadSpecialized(currentView),30)}
async function loadSpecialized(view){return;}
async function renderDashboard(){content.innerHTML=`<section class="page"><div class="page-intro"><h2>MELO</h2><p>Loading live control-room data…</p></div></section>`;try{const [d,r,accounts]=await Promise.all([api('/api/admin/dashboard'),api('/api/admin/releases').catch(()=>({rows:[]})),api('/api/admin/accounts').catch(()=>({rows:[],metrics:{}}))]);content.innerHTML=dashboardHtml(d,r,accounts)}catch(e){content.innerHTML=`<section class="page"><div class="page-intro"><h2>Unable to load dashboard</h2><p>${esc(e.message)}</p></div></section>`}}
function render(view,search=''){currentView=views[view]?view:'dashboard';document.querySelectorAll('.nav-item').forEach(a=>a.classList.toggle('active',a.dataset.view===currentView));title.textContent=views[currentView].title;history.replaceState(null,'',`/admin/?view=${currentView}${search?`&q=${encodeURIComponent(search)}`:''}`);if(currentView==='dashboard'){renderDashboard();return;}if(currentView==='services'){renderServices();return;}if(specializedViews.has(currentView)){window.dispatchEvent(new CustomEvent('controlroom:viewchange',{detail:{view:currentView}}));return;}content.innerHTML=`<section class="page"><div class="page-intro"><h2>${esc(views[currentView].heading)}</h2><p>Loading live control-room data…</p></div></section>`;api(`/api/admin/${currentView}`).then(d=>{content.innerHTML=dashboardHtml(d,{rows:[]})}).catch(e=>{content.innerHTML=`<section class="page"><div class="page-intro"><h2>Unable to load ${esc(views[currentView].heading)}</h2><p>${esc(e.message)}</p></div></section>`})}
function boot(){const params=new URLSearchParams(location.search);render(params.get('view')||'dashboard',params.get('q')||'')}
document.querySelectorAll('.nav-item').forEach(a=>a.addEventListener('click',e=>{const v=a.dataset.view;if(!v)return;e.preventDefault();render(v)}));
if(logout)logout.onclick=async()=>{try{await fetch('/api/admin/logout',{method:'POST',credentials:'include'})}finally{location.href='../admin-login.html'}};
if(identity)api('/api/admin/me').then(d=>{identity.textContent=d.email||d.identity||'Authenticated'}).catch(()=>{});
setInterval(()=>{if(clock)clock.textContent=new Date().toUTCString().slice(17,25)+' UTC'},1000);
boot();